{% set name = "sharrow" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sharrow-{{ version }}.tar.gz
  sha256: d4e6881f8abfe0719b009963c491285d14c61226c64382ded16b3ce3d6f232fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - dask-core
    - filelock
    - networkx
    - numba >=0.53
    - numexpr
    - numpy >=1.19
    - pandas >=1.2
    - pyarrow >=3.0.0
    - python >={{ python_min }}
    - xarray >=0.20.0
    - sparse

test:
  imports:
    - sharrow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ActivitySim/sharrow
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A compiler for ActivitySim-style utility specification files

extra:
  recipe-maintainers:
    - jpn--
